GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9obiIsImlhdCI6MTc0NDgyNjExOSwiZXhwIjoxNzQ0ODI2MTM0fQ.PV_Rc72m1zCKu_c5azDosCS7v_qO-AGc30R48c_pxL8


###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTc0NDgyNjIxMH0.o_dUq8Xq5EZ53wGSIE7823g_icNQqzFU4EmvHL1TTTw"
}
###
POST http://localhost:4000/token 
Content-Type: application/json

{
  "token":
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTc0NDgyNjIxMH0.o_dUq8Xq5EZ53wGSIE7823g_icNQqzFU4EmvHL1TTTw"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}

